<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="50" result="Failed" total="50" passed="31" failed="19" inconclusive="0" skipped="0" asserts="41" engine-version="3.4.1.0" clr-version="4.0.30319.42000" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:04Z" duration="0.314819">
  <command-line><![CDATA["D:\С#AutomationClasses\Module 3 Week 1\HW\packages\NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe"  "D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\bin\Debug\UnitTestProject1.dll"]]></command-line>
  <test-suite type="Assembly" id="0-1062" name="UnitTestProject1.dll" fullname="D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\bin\Debug\UnitTestProject1.dll" runstate="Runnable" testcasecount="50" result="Failed" site="Child" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.270326" total="50" passed="31" failed="19" inconclusive="0" skipped="0" asserts="41">
    <environment framework-version="3.4.1.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.10586.0" platform="Win32NT" cwd="D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\bin\Debug" machine-name="EPRUPETW6698" user="Natalia_Grebenshchik" user-domain="PETERSBURG" culture="en-US" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="WorkDirectory" value="D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\bin\Debug" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.5.2" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_PID" value="36644" />
      <property name="_APPDOMAIN" value="test-domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1063" name="UnitTestProject1" fullname="UnitTestProject1" runstate="Runnable" testcasecount="50" result="Failed" site="Child" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.250378" total="50" passed="31" failed="19" inconclusive="0" skipped="0" asserts="41">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestFixture" id="0-1000" name="UnitTest1" fullname="UnitTestProject1.UnitTest1" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="50" result="Failed" site="Child" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.244722" total="50" passed="31" failed="19" inconclusive="0" skipped="0" asserts="41">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="ParameterizedMethod" id="0-1020" name="AbsTest" fullname="UnitTestProject1.UnitTest1.AbsTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.052747" total="4" passed="3" failed="1" inconclusive="0" skipped="0" asserts="4">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1016" name="AbsTest(5)" fullname="UnitTestProject1.UnitTest1.AbsTest(5)" methodname="AbsTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="321754914" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.016661" asserts="1" />
          <test-case id="0-1017" name="AbsTest(-5)" fullname="UnitTestProject1.UnitTest1.AbsTest(-5)" methodname="AbsTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="147157561" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000078" asserts="1" />
          <test-case id="0-1018" name="AbsTest(0)" fullname="UnitTestProject1.UnitTest1.AbsTest(0)" methodname="AbsTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1591945647" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000073" asserts="1" />
          <test-case id="0-1019" name="AbsTest(-5.0236d)" fullname="UnitTestProject1.UnitTest1.AbsTest(-5.0236d)" methodname="AbsTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1827688094" result="Failed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.018227" asserts="1">
            <failure>
              <message><![CDATA[  Expected: 5.0236000000000001d
  But was:  5.0d
]]></message>
              <stack-trace><![CDATA[at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
]]></stack-trace>
            </failure>
          </test-case>
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1006" name="AddTest" fullname="UnitTestProject1.UnitTest1.AddTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="5" result="Failed" site="Child" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.022483" total="5" passed="0" failed="5" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1001" name="AddTest(1,1,2)" fullname="UnitTestProject1.UnitTest1.AddTest(1,1,2)" methodname="AddTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="431356040" result="Failed" label="Error" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.005538" asserts="0">
            <failure>
              <message><![CDATA[System.InvalidCastException : Specified cast is not valid.]]></message>
              <stack-trace><![CDATA[   at CSharpCalculator.Calculator.Add(Object a, Object b)
   at UnitTestProject1.UnitTest1.AddTest(Object a, Object b, Double expected) in D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\UnitTest1.cs:line 27]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1002" name="AddTest(1,2,3)" fullname="UnitTestProject1.UnitTest1.AddTest(1,2,3)" methodname="AddTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="589130677" result="Failed" label="Error" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000601" asserts="0">
            <failure>
              <message><![CDATA[System.InvalidCastException : Specified cast is not valid.]]></message>
              <stack-trace><![CDATA[   at CSharpCalculator.Calculator.Add(Object a, Object b)
   at UnitTestProject1.UnitTest1.AddTest(Object a, Object b, Double expected) in D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\UnitTest1.cs:line 27]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1003" name="AddTest(-1,1,0)" fullname="UnitTestProject1.UnitTest1.AddTest(-1,1,0)" methodname="AddTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="42303146" result="Failed" label="Error" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000564" asserts="0">
            <failure>
              <message><![CDATA[System.InvalidCastException : Specified cast is not valid.]]></message>
              <stack-trace><![CDATA[   at CSharpCalculator.Calculator.Add(Object a, Object b)
   at UnitTestProject1.UnitTest1.AddTest(Object a, Object b, Double expected) in D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\UnitTest1.cs:line 27]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1004" name="AddTest(2,3,5)" fullname="UnitTestProject1.UnitTest1.AddTest(2,3,5)" methodname="AddTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1055778587" result="Failed" label="Error" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000478" asserts="0">
            <failure>
              <message><![CDATA[System.InvalidCastException : Specified cast is not valid.]]></message>
              <stack-trace><![CDATA[   at CSharpCalculator.Calculator.Add(Object a, Object b)
   at UnitTestProject1.UnitTest1.AddTest(Object a, Object b, Double expected) in D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\UnitTest1.cs:line 27]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1005" name="AddTest(&quot;2&quot;,&quot;3&quot;,5)" fullname="UnitTestProject1.UnitTest1.AddTest(&quot;2&quot;,&quot;3&quot;,5)" methodname="AddTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="571943000" result="Failed" label="Error" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.001041" asserts="0">
            <failure>
              <message><![CDATA[System.InvalidCastException : Specified cast is not valid.]]></message>
              <stack-trace><![CDATA[   at CSharpCalculator.Calculator.Add(Object a, Object b)
   at UnitTestProject1.UnitTest1.AddTest(Object a, Object b, Double expected) in D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\UnitTest1.cs:line 27]]></stack-trace>
            </failure>
          </test-case>
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1027" name="CosTest" fullname="UnitTestProject1.UnitTest1.CosTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="6" result="Failed" site="Child" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.019864" total="6" passed="2" failed="4" inconclusive="0" skipped="0" asserts="6">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1021" name="CosTest(90)" fullname="UnitTestProject1.UnitTest1.CosTest(90)" methodname="CosTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="340721029" result="Failed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.001771" asserts="1">
            <failure>
              <message><![CDATA[  Expected: 0
  But was:  -0.44807361612917013d
]]></message>
              <stack-trace><![CDATA[at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1022" name="CosTest(-90)" fullname="UnitTestProject1.UnitTest1.CosTest(-90)" methodname="CosTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="386682285" result="Failed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000166" asserts="1">
            <failure>
              <message><![CDATA[  Expected: 0
  But was:  -0.44807361612917013d
]]></message>
              <stack-trace><![CDATA[at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1023" name="CosTest(-120)" fullname="UnitTestProject1.UnitTest1.CosTest(-120)" methodname="CosTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="2011583959" result="Failed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000145" asserts="1">
            <failure>
              <message><![CDATA[  Expected: -0.5d
  But was:  0.8141809705265618d
]]></message>
              <stack-trace><![CDATA[at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1024" name="CosTest(1.5707963267949d)" fullname="UnitTestProject1.UnitTest1.CosTest(1.5707963267949d)" methodname="CosTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="53161286" result="Failed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000318" asserts="1">
            <failure>
              <message><![CDATA[  Expected: 0
  But was:  6.1230317691118863E-17d
]]></message>
              <stack-trace><![CDATA[at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1025" name="CosTest(3.14159265358979d)" fullname="UnitTestProject1.UnitTest1.CosTest(3.14159265358979d)" methodname="CosTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1396848000" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000049" asserts="1" />
          <test-case id="0-1026" name="CosTest(0)" fullname="UnitTestProject1.UnitTest1.CosTest(0)" methodname="CosTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1427591365" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000065" asserts="1" />
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1015" name="DivideTest" fullname="UnitTestProject1.UnitTest1.DivideTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="3" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.009602" total="3" passed="3" failed="0" inconclusive="0" skipped="0" asserts="3">
          <test-case id="0-1012" name="DivideTest(1,1,1)" fullname="UnitTestProject1.UnitTest1.DivideTest(1,1,1)" methodname="DivideTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1034477846" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000667" asserts="1" />
          <test-case id="0-1013" name="DivideTest(1,2,0.5d)" fullname="UnitTestProject1.UnitTest1.DivideTest(1,2,0.5d)" methodname="DivideTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="526471793" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000097" asserts="1" />
          <test-case id="0-1014" name="DivideTest(-1,1,-1)" fullname="UnitTestProject1.UnitTest1.DivideTest(-1,1,-1)" methodname="DivideTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="746445533" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000096" asserts="1" />
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1039" name="IsNegativeTest" fullname="UnitTestProject1.UnitTest1.IsNegativeTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="5" result="Failed" site="Child" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.017528" total="5" passed="4" failed="1" inconclusive="0" skipped="0" asserts="5">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1034" name="IsNegativeTest(-1)" fullname="UnitTestProject1.UnitTest1.IsNegativeTest(-1)" methodname="IsNegativeTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1411126866" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.001815" asserts="1" />
          <test-case id="0-1035" name="IsNegativeTest(-1.000055698d)" fullname="UnitTestProject1.UnitTest1.IsNegativeTest(-1.000055698d)" methodname="IsNegativeTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="2046362008" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000075" asserts="1" />
          <test-case id="0-1036" name="IsNegativeTest(-1E-20.0d)" fullname="UnitTestProject1.UnitTest1.IsNegativeTest(-1E-20.0d)" methodname="IsNegativeTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1640205419" result="Failed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000562" asserts="1">
            <failure>
              <message><![CDATA[  Expected: False
  But was:  True
]]></message>
              <stack-trace><![CDATA[at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1037" name="IsNegativeTest(1)" fullname="UnitTestProject1.UnitTest1.IsNegativeTest(1)" methodname="IsNegativeTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="795096248" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000107" asserts="1" />
          <test-case id="0-1038" name="IsNegativeTest(1.36598779d)" fullname="UnitTestProject1.UnitTest1.IsNegativeTest(1.36598779d)" methodname="IsNegativeTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="177910340" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000080" asserts="1" />
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1045" name="IsPositiveTest" fullname="UnitTestProject1.UnitTest1.IsPositiveTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="5" result="Failed" site="Child" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.015963" total="5" passed="4" failed="1" inconclusive="0" skipped="0" asserts="5">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1040" name="IsPositiveTest(-1)" fullname="UnitTestProject1.UnitTest1.IsPositiveTest(-1)" methodname="IsPositiveTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1129699621" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000479" asserts="1" />
          <test-case id="0-1041" name="IsPositiveTest(-1.000055698d)" fullname="UnitTestProject1.UnitTest1.IsPositiveTest(-1.000055698d)" methodname="IsPositiveTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1504051068" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000138" asserts="1" />
          <test-case id="0-1042" name="IsPositiveTest(0)" fullname="UnitTestProject1.UnitTest1.IsPositiveTest(0)" methodname="IsPositiveTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="968900682" result="Failed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000261" asserts="1">
            <failure>
              <message><![CDATA[  Expected: True
  But was:  False
]]></message>
              <stack-trace><![CDATA[at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1043" name="IsPositiveTest(1)" fullname="UnitTestProject1.UnitTest1.IsPositiveTest(1)" methodname="IsPositiveTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1469266360" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000097" asserts="1" />
          <test-case id="0-1044" name="IsPositiveTest(1.36598779d)" fullname="UnitTestProject1.UnitTest1.IsPositiveTest(1.36598779d)" methodname="IsPositiveTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1845601914" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000165" asserts="1" />
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1051" name="MultiplyTest" fullname="UnitTestProject1.UnitTest1.MultiplyTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="5" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.015427" total="5" passed="5" failed="0" inconclusive="0" skipped="0" asserts="5">
          <test-case id="0-1046" name="MultiplyTest(10,15)" fullname="UnitTestProject1.UnitTest1.MultiplyTest(10,15)" methodname="MultiplyTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1164029842" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000327" asserts="1" />
          <test-case id="0-1047" name="MultiplyTest(-1,15)" fullname="UnitTestProject1.UnitTest1.MultiplyTest(-1,15)" methodname="MultiplyTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="2136536027" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000083" asserts="1" />
          <test-case id="0-1048" name="MultiplyTest(0.0005554d,15)" fullname="UnitTestProject1.UnitTest1.MultiplyTest(0.0005554d,15)" methodname="MultiplyTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="468872117" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000071" asserts="1" />
          <test-case id="0-1049" name="MultiplyTest(0,15)" fullname="UnitTestProject1.UnitTest1.MultiplyTest(0,15)" methodname="MultiplyTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="592474526" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000146" asserts="1" />
          <test-case id="0-1050" name="MultiplyTest(0,0)" fullname="UnitTestProject1.UnitTest1.MultiplyTest(0,0)" methodname="MultiplyTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1109219091" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000075" asserts="1" />
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1056" name="PowTest" fullname="UnitTestProject1.UnitTest1.PowTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.015549" total="4" passed="0" failed="4" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1052" name="PowTest(10,15)" fullname="UnitTestProject1.UnitTest1.PowTest(10,15)" methodname="PowTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1500613759" result="Failed" label="Error" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.001874" asserts="0">
            <failure>
              <message><![CDATA[System.NotFiniteNumberException : Wrong input]]></message>
              <stack-trace><![CDATA[   at CSharpCalculator.Calculator.Pow(Object a, Object b)
   at UnitTestProject1.UnitTest1.PowTest(Object a, Object b) in D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\UnitTest1.cs:line 122]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1053" name="PowTest(-1,14)" fullname="UnitTestProject1.UnitTest1.PowTest(-1,14)" methodname="PowTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="529437676" result="Failed" label="Error" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000652" asserts="0">
            <failure>
              <message><![CDATA[System.NotFiniteNumberException : Wrong input]]></message>
              <stack-trace><![CDATA[   at CSharpCalculator.Calculator.Pow(Object a, Object b)
   at UnitTestProject1.UnitTest1.PowTest(Object a, Object b) in D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\UnitTest1.cs:line 122]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1054" name="PowTest(0,15)" fullname="UnitTestProject1.UnitTest1.PowTest(0,15)" methodname="PowTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1615225705" result="Failed" label="Error" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000576" asserts="0">
            <failure>
              <message><![CDATA[System.NotFiniteNumberException : Wrong input]]></message>
              <stack-trace><![CDATA[   at CSharpCalculator.Calculator.Pow(Object a, Object b)
   at UnitTestProject1.UnitTest1.PowTest(Object a, Object b) in D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\UnitTest1.cs:line 122]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1055" name="PowTest(2,2)" fullname="UnitTestProject1.UnitTest1.PowTest(2,2)" methodname="PowTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1660230489" result="Failed" label="Error" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000542" asserts="0">
            <failure>
              <message><![CDATA[System.NotFiniteNumberException : Wrong input]]></message>
              <stack-trace><![CDATA[   at CSharpCalculator.Calculator.Pow(Object a, Object b)
   at UnitTestProject1.UnitTest1.PowTest(Object a, Object b) in D:\С#AutomationClasses\Module 3 Week 1\HW\UnitTestProject1\UnitTest1.cs:line 122]]></stack-trace>
            </failure>
          </test-case>
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1033" name="SinTest" fullname="UnitTestProject1.UnitTest1.SinTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="5" result="Failed" site="Child" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.015067" total="5" passed="3" failed="2" inconclusive="0" skipped="0" asserts="5">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1028" name="SinTest(1.5707963267949d)" fullname="UnitTestProject1.UnitTest1.SinTest(1.5707963267949d)" methodname="SinTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1106076452" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000526" asserts="1" />
          <test-case id="0-1029" name="SinTest(4.71238898038469d)" fullname="UnitTestProject1.UnitTest1.SinTest(4.71238898038469d)" methodname="SinTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="669047137" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000053" asserts="1" />
          <test-case id="0-1030" name="SinTest(0.523598775598299d)" fullname="UnitTestProject1.UnitTest1.SinTest(0.523598775598299d)" methodname="SinTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1496593224" result="Failed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000311" asserts="1">
            <failure>
              <message><![CDATA[  Expected: 0.5d
  But was:  0.49999999999999994d
]]></message>
              <stack-trace><![CDATA[at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1031" name="SinTest(3.14159265358979d)" fullname="UnitTestProject1.UnitTest1.SinTest(3.14159265358979d)" methodname="SinTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="2095063934" result="Failed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000171" asserts="1">
            <failure>
              <message><![CDATA[  Expected: 0
  But was:  1.2246063538223773E-16d
]]></message>
              <stack-trace><![CDATA[at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1032" name="SinTest(0)" fullname="UnitTestProject1.UnitTest1.SinTest(0)" methodname="SinTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="291836545" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000096" asserts="1" />
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1061" name="SqrtTest" fullname="UnitTestProject1.UnitTest1.SqrtTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.012709" total="4" passed="3" failed="1" inconclusive="0" skipped="0" asserts="4">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1057" name="SqrtTest(4)" fullname="UnitTestProject1.UnitTest1.SqrtTest(4)" methodname="SqrtTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="996934114" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000404" asserts="1" />
          <test-case id="0-1058" name="SqrtTest(4)" fullname="UnitTestProject1.UnitTest1.SqrtTest(4)" methodname="SqrtTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1659826362" result="Failed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000228" asserts="1">
            <failure>
              <message><![CDATA[  Expected: -2
  But was:  2.0d
]]></message>
              <stack-trace><![CDATA[at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1059" name="SqrtTest(0)" fullname="UnitTestProject1.UnitTest1.SqrtTest(0)" methodname="SqrtTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="252432214" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000076" asserts="1" />
          <test-case id="0-1060" name="SqrtTest(-1)" fullname="UnitTestProject1.UnitTest1.SqrtTest(-1)" methodname="SqrtTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="884605553" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000122" asserts="1" />
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1011" name="SubTest" fullname="UnitTestProject1.UnitTest1.SubTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" testcasecount="4" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.012692" total="4" passed="4" failed="0" inconclusive="0" skipped="0" asserts="4">
          <test-case id="0-1007" name="SubTest(1,1,0)" fullname="UnitTestProject1.UnitTest1.SubTest(1,1,0)" methodname="SubTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="990907487" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000460" asserts="1" />
          <test-case id="0-1008" name="SubTest(1,2,-1)" fullname="UnitTestProject1.UnitTest1.SubTest(1,2,-1)" methodname="SubTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="349740297" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000050" asserts="1" />
          <test-case id="0-1009" name="SubTest(-1,1,-2)" fullname="UnitTestProject1.UnitTest1.SubTest(-1,1,-2)" methodname="SubTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1678033440" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000046" asserts="1" />
          <test-case id="0-1010" name="SubTest(2,3,-1)" fullname="UnitTestProject1.UnitTest1.SubTest(2,3,-1)" methodname="SubTest" classname="UnitTestProject1.UnitTest1" runstate="Runnable" seed="1351014472" result="Passed" start-time="2016-07-15 16:57:03Z" end-time="2016-07-15 16:57:03Z" duration="0.000044" asserts="1" />
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>